version: '2'
services:
  spring: 
    build: .
    network_mode: host
    ports:
    - '8005:8005'
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:4'
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - REDMINE_PASSWORD=admin
      - REDMINE_USERNAME=admin
    ports:
      - '8090:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   ports:
  #     - 5432:5434
  #   environment:
  #     POSTGRES_PASSWORD: 'postgres'
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
  postgres_data:
    driver: local